project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - FigureS1.qmd
    - FigureS2.qmd
    # Any file not listed here will be ignored by the build process

execute:
  freeze: auto

website:
  title: "MCD 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FigureS1.qmd
        text: Figure S1
      - href: FigureS2.qmd
        text: Figure S2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


