project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Figure1.qmd
    - Figure2.qmd
    # Any file not listed here will be ignored by the build process

execute:
  freeze: auto

website:
  title: "MCD 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Figure1.qmd
      - Figure2.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


