---
title: "Figure 2"
---


```{r include=FALSE, warning = FALSE}
library(dplyr)
library(geojp)
library(sf)
library(leaflet)
```

```{r include=FALSE}
N03_small <- sf::read_sf(here::here("data","N03_small.geojson"))
N03_okinawa_amami <- sf::read_sf(here::here("data","N03_okinawa_amami.geojson"))
N03_small <- rbind(N03_small, N03_okinawa_amami)
A38 <- sf::read_sf(here::here("data","A38_small.geojson"))
# A38 <- sf::read_sf(here::here("data","A38_small_nori.geojson"))
A38_nocentre <- dplyr::filter(A38, 
                      A38b_003 == 102 |
                      A38b_003 == 103 |
                      A38b_003 == 106 |
                      A38b_003 == 108 |
                      A38b_003 == 114 |
                      A38b_003 == 115 |
                      A38b_003 == 116 |
                      A38b_003 == 1313 |
                      A38b_003 == 1704 |
                      A38b_003 == 1802 |
                      A38b_003 == 1803 |
                      A38b_003 == 1903 |
                      A38b_003 == 2311 |
                      A38b_003 == 2507 |
                      A38b_003 == 2902 |
                      A38b_003 == 2905 |
                      A38b_003 == 4102 |
                      A38b_003 == 4506  )
MCD <- sf::read_sf(here::here("data","MCD.csv"), 
        options = c("X_POSSIBLE_NAMES=X", "Y_POSSIBLE_NAMES=Y"), 
        crs = 6668)
MCD$Type <- ifelse(MCD$Type == 2, 1, MCD$Type)
MCD$Type <- factor(MCD$Type, levels = c(1,3,4), labels=c("Core","Regional","Affiliated"))
MCD <- MCD[MCD$code_pref %in% c("16", "17", "18", "21", "23", "24", "25", "26"), ]
sfLabel <- sf::read_sf(here::here("data","label_SHA.geojson"))
```

```{r include=FALSE}
Catchment <- sf::read_sf(here::here("data","MCD_isochrones.geojson"))
Catchment$Catchment <- factor(Catchment$value,
                        levels=c(10000,30000),
                        labels=c("30 kilometre by car from MCD","10 kilometre by car from MCD")
                        )
```

```{r include=FALSE}
A22 <- sf::read_sf(here::here("data","A22_small.geojson"))
A22$Snowfall <- factor(A22$A22_009,
                        levels = c("1","2"),
                        labels = c("Heavy","Exteremely heavy"))
A24 <- sf::read_sf(here::here("data","A24_small.geojson"))
A24_okinawa_amami <- sf::read_sf(here::here("data","A24_okinawa_amami.geojson"))
A24 <- rbind(A24, A24_okinawa_amami)
A25 <- sf::read_sf(here::here("data","A25_small.geojson"))
A25_okinawa_amami <- sf::read_sf(here::here("data","A25_okinawa_amami.geojson"))
A25 <- rbind(A25, A25_okinawa_amami)
A18 <- sf::read_sf(here::here("data","A18_small.geojson"))
```

```{r include=FALSE}
dfRI <- sf::read_sf(here::here("data","rito.csv"))
sfRI_small <- dplyr::right_join(N03_small, dfRI,  
        by = dplyr::join_by(N03_007 == code_pref_muni))
```

```{r include=FALSE}
library(leaflet)
library(leaflet.extras)
bb <- sf::st_bbox(Catchment)
pal_MCD <- colorFactor(
  palette = c("#e853b2", "#2e33a6", "#459a64"),
  domain = MCD$Type
)
pal_Catchment <- colorFactor(
  palette = c("lightgreen", "darkgreen"),
  domain = Catchment$Catchment
)
pal_A22 <- colorFactor(
  palette = c("#8da5ed","#1a2a7f"),
  domain = A22$Snowfall
)
A24$Mountainous <- "Mountainous"
pal_A24 <- colorFactor(
  palette = c("#e59866"),
  domain = A24$Mountainous
)
A25$Agricultural <- "Agricultural"
pal_A25 <- colorFactor(
  palette = c("#82e0aa"),
  domain = A25$Agricultural
)
A18$Peninsula <- "Peninsula"
pal_A18 <- colorFactor(
  palette = c("#66cccc"),
  domain = A18$Peninsula
)

jp_map <- leaflet()
jp_map <- addTiles(jp_map, 
                   urlTemplate = "https://cyberjapandata.gsi.go.jp/xyz/english/{z}/{x}/{y}.png",
                   options = tileOptions(opacity = 0.5))
jp_map <- addPolygons(jp_map, data=N03_small, fillColor=NA, color="lightgrey", group="Municipalicty")
jp_map <- addPolygons(jp_map, data=A22, color=~pal_A22(Snowfall), group="Snowfall") #Snowfall
jp_map <- addPolygons(jp_map, data=A24, color=~pal_A24(Mountainous), group="Mountainous")
jp_map <- addPolygons(jp_map, data=A25, group="Agricultural")
jp_map <- addPolygons(jp_map, data=A18, group="Peninsula")
jp_map <- addPolygons(jp_map, data=A38_nocentre, fillColor=NA, color="red", group="SHA")
jp_map <- addPolygons(jp_map, data=Catchment, color=~pal_Catchment(Catchment), group="Catchment")
jp_map <- addCircles(jp_map, data=MCD, stroke = FALSE, fillColor=~pal_MCD(Type), fillOpacity = 1, radius =1000, group="MCD")
# jp_map <- addLegend(jp_map, pal=pal_A22, values=A22$Snowfall, title="Snowfall")
# jp_map <- addLegend(jp_map, pal=pal_A24, values=A24$Mountainous, title="Mountainous")
# jp_map <- addLegend(jp_map, pal=pal_A25, values=A25$Agricultural, title="Agricultural")
# jp_map <- addLegend(jp_map, pal=pal_A18, values=A18$Peninsula, title="Peninsula")
jp_map <- addLegend(jp_map, pal=pal_Catchment, values=Catchment$Catchment, title="Catchment")
jp_map <- addLegend(jp_map, pal=pal_MCD, values=MCD$Type, title="MCD")
jp_map <- addLayersControl(jp_map, 
            overlayGroups = c("Snowfall", "Mountainous", "Agricultural", "Peninsula", "SHA", "Catchment", "MCD"))
jp_map <- hideGroup(jp_map, c("Snowfall", "Mountainous", "Agricultural", "Peninsula", "SHA"))
jp_map <- fitBounds(jp_map, lng1 = unname(bb["xmin"]), lat1 = unname(bb["ymin"]), lng2 = unname(bb["xmax"]), lat2 = unname(bb["ymax"]))
jp_map <- addFullscreenControl(jp_map)

```

```{r echo=FALSE}
jp_map
```
