---
title: "Count MCDs"
---

## Prerequisites

```{r include=FALSE}
library(here)
library(dplyr)
library(sf)
```

## Read Data

```{r include=FALSE}
sf::sf_use_s2(FALSE)

MCD <- sf::read_sf(here::here("data","MCD.csv"), 
        options = c("X_POSSIBLE_NAMES=X", "Y_POSSIBLE_NAMES=Y"), 
        crs = 6668)
MCD$Type <- ifelse(MCD$Type == 2, 1, MCD$Type)
MCD$Type <- factor(MCD$Type, levels = c(1,3,4), labels=c("Core","Regional","Affiliated"))

MCD_Core <- dplyr::filter(MCD, Type == "Core")
MCD_Reg <- dplyr::filter(MCD, Type == "Regional")
MCD_Col <- dplyr::filter(MCD, Type == "Affiliated")

N03_small <- sf::read_sf(here::here("data","N03_small.geojson"))
N03_okinawa_amami <- sf::read_sf(here::here("data","N03_okinawa_amami.geojson"))
N03 <- rbind(N03_small,N03_okinawa_amami)
A38 <- sf::read_sf(here::here("data","A38_small.geojson"))
A38_okinawa <- sf::read_sf(here::here("data","A38_okinawa_amami.geojson"))
A38 <- rbind(A38, A38_okinawa)
N03_A38 <- readr::read_csv(here::here("data","N03_A38.csv"))
```

## Count

```{r include=FALSE}
N03$Core <- lengths(sf::st_intersects(N03,MCD_Core))
N03$Regional <- lengths(sf::st_intersects(N03,MCD_Reg))
N03$Collaborative <- lengths(sf::st_intersects(N03,MCD_Col))
N03$total <- N03$Core + N03$Regional + N03$Collaborative

A38$SHA_Core <- lengths(sf::st_intersects(A38,MCD_Core))
A38$SHA_Regional <- lengths(sf::st_intersects(A38,MCD_Reg))
A38$SHA_Collaborative <- lengths(sf::st_intersects(A38,MCD_Col))
A38$SHA_total <- A38$SHA_Core + A38$SHA_Regional + A38$SHA_Collaborative
```


## Link N03 (municipality) and A38 (SHA)

The municipalities to be omitted:
1695
1696
1697
1698
1699
1700
12801
13801
13803
13805
13807
23801
46801
47801

```{r include=FALSE}
library(dplyr)
N03 <- dplyr::left_join(N03, N03_A38, 
                        by = join_by("N03_007" == "A38b_001"))
N03 <- na.omit(N03)
N03 <- dplyr::left_join(N03, sf::st_drop_geometry(A38), 
                        by = join_by("A38b_003" == "A38b_003"))
readr::write_csv(sf::st_drop_geometry(N03), "shp/N03_count.csv")
```

